### ISSUE TITLE
It is possible that the HTTP Clinet connection was not reclaimed

### ISSUE THREAD

**Issue by za123** [Ponita0/PoniLCU#18]
Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at PoniLCU.LeagueClient.Request(requestMethod method, String url, Object body)
   at lolData.LolClient.gameCollect() in F:\reps\lolData\LolClient.cs:line 261

###
My request rate is one per second

**Comment by Ponita0** [comment]
what are you trying to do exactly because i think it might be against TOS

**Comment by za123** [comment]
I want to get my self all game history.

**Comment by za123** [comment]
including game details.When I slow down,it`s ok !

**Comment by za123** [comment]
I have a program the request fast and more,but the program it`s ok,so,I think the question in httpClient.
Or it could be my fault，I'm not very familiar with it C#。
